import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { cn } from '../lib/utils';
import './globals.css';

import { LightDarkToggle } from '../components/ui/light-dark-toggle';
import { Toaster } from '@/components/ui/toaster';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, 'bg-background')}>
        {children}

        <LightDarkToggle className="fixed top-[calc(50%-12px)] right-2" />
        <Toaster />
      </body>
    </html>
  );
}
